In [2]:
d1={"name":"sureka","rollno":154,"dept":"aiml"}
print(d1)
print(d1.keys())
d1["department"]=d1.pop("dept")
print(d1)

{'name': 'sureka', 'rollno': 154, 'dept': 'aiml'}
dict_keys(['name', 'rollno', 'dept'])
{'name': 'sureka', 'rollno': 154, 'department': 'aiml'}

In [1]:
data1={
    "name":["sureka","ranjana","tharshini","alfiya","charu","alshifa"],
    "age":[19,20,21,19,20,21],
    "dept":["ecs","cs","aiml","aiml","it","cs"]
    }
print(data1)

{'name': ['sureka', 'ranjana', 'tharshini', 'alfiya', 'charu', 'alshifa'], 'age': [19, 20, 21, 19, 20, 21], 'dept': ['ecs', 'cs', 'aiml', 'aiml', 'it', 'cs']}

In [2]:
import pandas as p
df1=p.DataFrame(data1)
df1

        name  age  dept
0     sureka   19   ecs
1    ranjana   20    cs
2  tharshini   21  aiml
3     alfiya   19  aiml
4      charu   20    it
5    alshifa   21    cs

In [3]:
df1.head(3)

        name  age  dept
0     sureka   19   ecs
1    ranjana   20    cs
2  tharshini   21  aiml

In [4]:
df1.tail(2)

      name  age dept
4    charu   20   it
5  alshifa   21   cs

In [5]:
df1["name"]

0       sureka
1      ranjana
2    tharshini
3       alfiya
4        charu
5      alshifa
Name: name, dtype: str

In [8]:
df1

      name  age  dept
0   sureka   19   ecs
1  ranjana   20    cs
2   kaniga   21  aiml
3   alfiya   19  aiml
4    charu   20    it
5  alshifa   21    cs